RANDOM_INIT_CAPTION = [
    'Loading chiptune tunes',
    'Loading scarily hostile bandits',
    'Loading awesome cutscenes',
    'Loading fragile spaceships',
    'Loading trusty gadgets',
    'Loading breakable terrain',
    'Loading troublesome hazzards',
    'Loading underused particles',
    'Loading overused items',
    'Loading friendly aliens',
    'Loading iconic shenanigans',
    'Loading you, yes, you!',
    'Loading Doom!... Not really',
    'Loading something, but I wont tell you :)',
    'Unloading the butterfly',
    'Preparing for another galaxy trip',
    'His name is Alt, and hers is Zia!',
    "To Western the Raid",
    "To Raid the Western",
    "Hello World!",
    "It's tumble or be tumbled",
    "Press K on menu! (meow)",
    "Press R after victory! (rave !!~)",
    "Retro is Love, Retro is Life",
    "Cowboys + Aliens = Peak",
    "Pineapple + Pizza = Drama",
    "Nerd + Meanie = Any anime ever",
    "9 + 10 = ...you finish it.",
    'Even though the sky...',
    'All hail my favourite number: 57',
    'You is awsome! (/^▽^)/ ~ ✿ ♡',
    'Avoiding school like a GAMER',
    'Going to school like a GAMER',
    'Remember to drink water!',
    'Remember to eat water!',
    'Remember to water the drink!',
    'Inspired by Breakout!',
    'Also inspired by Pizza Tower!',
    'This is a caption! Wowie!',
]